
#Common configuration settings
[common]
	#Allow all items to be added
	allitems = false
	#Whitelisted items
	items = ["tconstruct:materials_and_you", "theoneprobe:probenote", "integrateddynamics:on_the_dynamics_of_integration"]
	#Whitelisted names
	names = ["book", "tome", "lexicon", "nomicon", "manual", "knowledge", "pedia", "compendium", "guide", "codex", "journal"]
	#Mod aliases
	aliases = ["thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "redstonearsenal=thermalfoundation", "rftoolsdim=rftools", "rftoolspower=rftools", "rftoolscontrol=rftools", "xnet=rftools"]
	#Blacklisted mods
	exclude = []

