name = "Eccentric Pack"
author = "EccentricVamp"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14bde5bf8734bf79971b634a69d09a676454cb0c69f89b85ba692a8fcb607558"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
