name = "Eccentric Pack"
author = "EccentricVamp"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96e507ec4b0ca7f4178062131851b44af17096f865432e8dda561f8996b15b76"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
